### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by suchmememanyskill** [Vampitech/NeXT#2]
Your AIO (All In One) includes TegraExplorer and Sys-Dvr without linking their sources. You also do not include any licenses of any of the used programs in your final zip. You also probably want this repository to be licensed under GPLv2. Please fix

Also note, you are modifying TegraExplorer's source. You need to disclose this too

**Comment by Vampitech** [comment]
Well, this issue surprise me a lot for 3 things. 1.You are the first dev to make a complain about this, that's good, i understand the ethical reasons for that and i don't have any problem in order to be compliant and fair. 2. Many AIOs like mine doesn't includes any licensing of the projects that are using on it and i don't have any problem about the things that you are asking for. But i'm gonna be honest, i don't see fair that this issue are being addressed just to me while others AIOs projects who doesn't have any licensing at in their final zips. It's really extrange, but meh!. 3. The only modifications that i did on TegraExplorer is just changing the "Reboot to Atmosphere" and "Reboot to Hekate" texts to "Reboot To NeXT" and changing the path of the target payload, That's all. The entire project stills untouched. 

But anyway, i have take the actions being consistent with  your suggestions in order to be fair with the devs cause i recognize your hard work and for that reason I will never take credit for things that are not mine.

Now, if after that you feel that i still taking credit of your work or violating some licensing, just let me know about that to take TegraExplorer out of my AIO.
